name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      # Step 3: Prepare the `dist` folder
      - name: Prepare files for deployment
        run: |
          mkdir -p dist
          cp index.html dist/
          cp css/ dist/
          cp js/ dist/
          cp $(go env GOROOT)/misc/wasm/wasm_exec.js dist/
          GOOS=js GOARCH=wasm go build -o dist/main.wasm main.go

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
